---
title: "cmdr stats server"
author: "Guy Schnidrig"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  flexdashboard::flex_dashboard:
    theme: flatly
    orientation: columns
    vertical_layout: fill

runtime: shiny
---

```{r global, setup, include = FALSE, echo = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load Libraries
library(tidyverse)
library(plotly)
library(readxl)
library(flextable)
library(shiny)
library(flexdashboard)
library(jsonlite)
library(httr)
library(data.table)
library(dtplyr)
library(googlesheets4)
library(RColorBrewer)
library(png)

# Misc
Sys.setenv(LANG = "en")
rm(list=ls())
gc()
set.seed(42)
options(scipen = 999,
        dplyr.summarise.inform = FALSE)

# Authenticate using token. 
gs4_auth(cache = ".secrets", email = "g.schnidu@gmail.com")

# Write to sheet
#ss <- gs4_get("https://docs.google.com/spreadsheets/d/1yMb2ijZfeAcAVHBNJGTcnORYu4GPSBTlDTioDQkoB1c/edit#gid=1318392544")
#sheet_append(ss, data.frame(time=Sys.time()))



# Game Data
data <- read_sheet("https://docs.google.com/spreadsheets/d/1yMb2ijZfeAcAVHBNJGTcnORYu4GPSBTlDTioDQkoB1c/edit#gid=1318392544")

color_list <- c("#fd7f6f", "#7eb0d5", "#b2e061", "#bd7ebe", "#ffb55a", "#ffee65", "#beb9db", "#8bd3c7")
player_color_mapping <- data.frame(Player = unique(data$Player), Color = color_list)



```


```{r data setup, include = FALSE, echo = FALSE, warning = FALSE}
# Set Deck ID
data <- data %>%
  group_by(Deck_Link) %>%
  mutate(Deck_ID = cur_group_id()) %>%
  ungroup()

# Set Factors
cols <- c("Game_ID","Game_Type", "Player", "Commander", "Colors", "Win_Type", "MV_Card", "Deck_ID")
data[cols] <- lapply(data[cols], factor)

# Set Date
data$Date <- lubridate::dmy(data$Date)

# Get Deck links
deck_list <- data %>%
  filter(grepl("archidekt", Deck_Link)) %>%
  select(Deck_Link, Deck_ID) %>%
  distinct(Deck_Link, Deck_ID)

# Add right api path and ending
deck_list$Deck_Link <- deck_list$Deck_Link %>%
  str_replace(.,"decks", "api/decks") %>%
  str_replace(.,"www.", "") %>%
  gsub("#.*", "", .)

deck_list <- deck_list %>%
  mutate(Deck_Link_clean = paste0(Deck_Link,"/")) %>%
  select(-Deck_Link) %>% 
  distinct()

data <- left_join(data, deck_list, by = "Deck_ID") 

# Get Deck lists
res_list <- lapply(deck_list$Deck_Link_clean, httr::GET)
json_text_list <- lapply(res_list, content, as = "text", encoding = "UTF-8") 
json_data_list <- lapply(json_text_list, fromJSON)

quantity_list <- lapply(json_data_list, function(i) {
  x = i$cards$quantity 
  z = i$cards$card$oracleCard$cmc
  g = i$cards$card$oracleCard$salt
  p = i$cards$card$prices$tcg
  n = i$cards$card$oracleCard$name
  d = i$name
  name <- tibble(d,n,x,z,g,p) %>%
  rename(deck_name = d,
         card_name = n,
         Quantity = x,
         cmc = z,
         salt = g,
         price = p)})

commander_decks <- quantity_list

# rename the list items
names(commander_decks) <- c(deck_list$Deck_Link_clean)

# add link to data frame
commander_decks <- Map(cbind, commander_decks, Deck_Link_clean=names(commander_decks))

# Create data frame with all decks
all_decks <- data.table::rbindlist(commander_decks)

deck_infos <- data %>%
   select(Deck_Link_clean, Commander, Player, Deck_ID) %>% 
  distinct() %>% 
  drop_na()

all_decks_join <- left_join(all_decks, deck_infos, by = "Deck_Link_clean")

all_decks_join <- all_decks_join %>%
  group_by(Player) %>%
  mutate(Number_of_decks = length(unique(Deck_ID))) %>% 
  ungroup()

```

# Dashboard
Column {data-width=650}
-----------------------------------------------------------------------

### Games played
```{r, echo = FALSE}
ggplotly(
  data %>%
  filter(Game_Type != "Draft") %>%
  group_by(Player) %>%
  summarise(Played_Games = length(Game_ID)) %>%
  ggplot(aes(x = reorder(Player,-Played_Games), y = Played_Games, fill = Player)) +
  geom_bar(stat = "identity") +
  labs(x = "", y = "Games Played") + 
  scale_fill_manual(values = player_color_mapping$Color) +
  theme_bw()
) 
```

### Total Games Won
```{r, echo = FALSE}
data %>%
  filter(Game_Type != "Draft") %>%
  filter(Win >= 1) %>%
  plot_ly(., 
          labels = ~Player, 
          values = ~Win, 
          type = 'pie') %>%  
          layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                 yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

```

Row
-----------------------------------------------------------------------

### Statistics

```{r, echo = FALSE}
data %>%
  filter(Game_Type != "Draft") %>%
  summarise(`Total Games` = length(unique(Game_ID)),
            `Unique Players` = length(unique(Player)),
            `Unique Commanders` = length(unique(Commander)),
            `Average Win Turn` = mean(Win_Turn, na.rm = TRUE),
            `Most played Color` = names(which.max(table(.$Colors)))) %>%
  knitr::kable()
```

```{r, echo = FALSE}
most_played_card <- all_decks_join %>% 
  filter(cmc != 0) %>% 
  group_by(card_name) %>%
  count() %>% 
  ungroup() %>% 
  arrange(desc(n)) %>%
  slice_head(n = 5)


all_decks_join %>%
  filter(cmc != 0) %>% 
  distinct(Deck_ID, .keep_all = TRUE) %>% 
  summarise(`Average cmc` = mean(cmc),
            `Average salt score` = mean(salt),
            `Average price (tcg)` = mean(price)) %>%
  mutate(`1st played card` = most_played_card$card_name[1],
         `2nd played card` = most_played_card$card_name[2],) %>%
  mutate(across(where(is.numeric), round, 2)) %>% 
  knitr::kable()
```


```{r, echo = FALSE}
 data %>% 
  filter(Game_Type != "Draft") %>%
  group_by(Commander) %>%
  summarise(`Games played` = length(Commander),
            Wins = sum(Win, na.rm = T)) %>%
  arrange(desc(`Games played`)) %>%
  slice_head(n = 5)%>%
  knitr::kable()
```

### Mana Value Distribution of all decks played

```{r,echo=FALSE}
deck_cmc <- all_decks_join %>%
  group_by(Player, cmc, Number_of_decks) %>%
  summarize(Average_Number_Spells = (mean(n_distinct(card_name))))


deck_cmc_average <- deck_cmc %>%
  summarise(Average_Number_Spells = (Average_Number_Spells) / Number_of_decks)
  

ggplotly(deck_cmc_average %>%
  filter(cmc > 0) %>%
  ggplot(aes(y = Average_Number_Spells, x = cmc, fill = Player)) +
  geom_bar(position="dodge", stat="identity") + 
    scale_fill_manual(values = player_color_mapping$Color) +
    facet_wrap(~Player) + 
    scale_x_continuous(breaks = seq(min(deck_cmc_average$cmc, na.rm = T), max(deck_cmc_average$cmc, na.rm = T), by = 1)) +
    theme_bw())
```



# Game data

```{r, echo=FALSE}
DT::datatable(data, filter = 'top')
```

# Deck data
```{r, echo=FALSE}
DT::datatable(all_decks_join, filter = 'top')
```

# Graphs
Column {data-width=650}
-----------------------------------------------------------------------
### Games played
```{r, echo = FALSE}
ggplotly(data %>%
           filter(Game_Type != "Draft") %>%  
           group_by(Player) %>%
           summarise(`Played Games` = length(Game_ID)) %>%
           ggplot(aes(x = reorder(Player,-`Played Games`), y = `Played Games`, fill = Player)) +
           geom_bar(stat='identity') +
           scale_fill_manual(values = player_color_mapping$Color) +
           labs(x = "", y = "Games Played") +
           theme_bw())
 
```

### Relative Games Won By Player
```{r RGW, echo=FALSE}
ggplotly(data %>%
           filter(Game_Type != "Draft") %>%
  group_by(Player) %>%
  summarise(
    gl = length(unique(Game_ID)),
Won_games_relative = (sum(Win, na.rm = TRUE) / length(unique(Game_ID)))) %>%
  ggplot(aes(x = reorder(Player,-Won_games_relative), y = Won_games_relative, fill = Player)) +
  geom_bar(stat='identity') +
  scale_fill_manual(values = player_color_mapping$Color) +
  labs(x = "", y = "Games Won (Relative)") +
  theme_bw())
```
Row
-----------------------------------------------------------------------

### Total Games Won By Commander And Player
```{r Commander, echo=FALSE}
ggplotly(data %>%
           filter(Game_Type != "Draft") %>%
           group_by(Commander, Player) %>%
           summarise(Won_Games = (sum(Win, na.rm = TRUE))) %>%
           filter(Won_Games >= 1) %>%
           ggplot(aes(x = reorder(Commander,-Won_Games), y = Won_Games, fill = Player)) +
           geom_bar(stat='identity') +
           scale_fill_manual(values = player_color_mapping$Color) +
           labs(x = "", y = "Games_Won") +
           theme_bw() + 
           theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))

```

### Total Games Won By Color And Player
```{r Colorwin, echo=FALSE}
ggplotly(data %>%
           filter(Game_Type != "Draft") %>%
           group_by(Colors, Player) %>%
           summarise(Won_Games = (sum(Win, na.rm = TRUE))) %>%
           filter(Won_Games >= 1) %>%
           ggplot(aes(x = reorder(Colors,-Won_Games), y = Won_Games, fill = Player)) +
           geom_bar(stat = "identity") +
           scale_fill_manual(values = player_color_mapping$Color) +
           labs(x = "", y = "Games_Won") +
           theme_bw() + 
           theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))
```

# Player
Column {.sidebar}
--------------------------------------------------
Hey there! 😄 Before we continue, I need a bit of your magic to complete the spell. 
Could you kindly whisper your enchanting name into the digital cauldron below.
```{r slider input, echo=FALSE}
selectInput(
  "Player", label = "Player:",
  choices = c(unique(data$Player)), selected = "Aless")

selectInput(
  "Game_Type", label = "Gametype:",
  choices = c("Normal", "With_Draft") , selected = "Normal")

```

Column
--------------------------------------------------
### Stats
```{r player stats, echo=FALSE}
renderTable({
  data %>%
    filter(Player == input$Player &  Game_Type != ifelse(input$Game_Type == "Normal", "Draft", "")) %>% 
    summarise(`Total Games` = length(unique(Game_ID)),
            `Unique Commanders` = length(unique(Commander)),
            `Average Win Turn` = mean(Win_Turn, na.rm = TRUE),
            `Most played Color` = names(which.max(table(.$Colors)))) %>% 
    as.data.table() })
```
### Stats 2
```{r player stats2, echo=FALSE}
renderTable({ data %>% 
  filter(Player == input$Player & Game_Type != ifelse(input$Game_Type == "Normal", "Draft", "")) %>%
  group_by(Commander) %>%
  summarise(`Games played` = length(Commander),
            Wins = as.integer(sum(Win, na.rm = T)),
            Winrate = Wins / `Games played`) %>%
  arrange(desc(`Games played`)) %>% 
    as.data.table()})
```

Row
-----------------------------------------------------------------------


### Image
```{r player image, echo=FALSE}
# 
# renderPlot({ 
#   t <- data %>% 
#   filter(Player == input$Player & Game_Type != ifelse(input$Game_Type == "Normal", "Draft", "")) %>%
#   group_by(Commander) %>%
#   summarise(`Games played` = length(Commander)) %>%
#   arrange(desc(`Games played`)) %>% 
#   slice(1)
#   
#   card_name <- as.character(t[[1]])
#   
#   scryfall_url <- paste0("https://api.scryfall.com/cards/named?fuzzy=", URLencode(card_name))
#   response <- GET(scryfall_url)
#   card_info <- content(response, "parsed")
#   image_url <- card_info$image_uris$normal
#   download.file(image_url, destfile = "mtg_card.jpg")
#   image <- readJPEG("mtg_card.jpg")
# 
#   dd <- data.frame(x = rnorm(100), y = rnorm(100))
#   gg <- ggplot(dd, aes(x, y)) +
#     geom_point() +
#     annotation_custom(rasterGrob(img), xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf)
# })


```

